// <auto-generated />
using JO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace JO.Data.Migrations
{
    [DbContext(typeof(VirtualPetContext))]
    [Migration("20170721195312_VirtualPet")]
    partial class VirtualPet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-preview2-25794");

            modelBuilder.Entity("JO.Data.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnimalTypeId");

                    b.Property<float>("CurrentHappiness");

                    b.Property<float>("CurrentHunger");

                    b.Property<string>("Name");

                    b.Property<int?>("UserId");

                    b.HasKey("AnimalId");

                    b.HasIndex("AnimalTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("JO.Data.AnimalStats", b =>
                {
                    b.Property<int>("AnimalStatsId")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("HappinessDecreaseRate");

                    b.Property<float>("HappinessIncreaseRate");

                    b.Property<float>("HungerDecreaseRate");

                    b.Property<float>("HungerIncreaseRate");

                    b.Property<float>("MaxHappiness");

                    b.Property<float>("MaxHunger");

                    b.Property<float>("MinHappiness");

                    b.Property<float>("MinHunger");

                    b.HasKey("AnimalStatsId");

                    b.ToTable("AnimalStats");
                });

            modelBuilder.Entity("JO.Data.AnimalType", b =>
                {
                    b.Property<int>("AnimalTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MetricId");

                    b.Property<int?>("StatsAnimalStatsId");

                    b.Property<string>("Type");

                    b.HasKey("AnimalTypeId");

                    b.HasIndex("StatsAnimalStatsId");

                    b.ToTable("AnimalTypes");
                });

            modelBuilder.Entity("JO.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JO.Data.Animal", b =>
                {
                    b.HasOne("JO.Data.AnimalType", "Type")
                        .WithMany()
                        .HasForeignKey("AnimalTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JO.Data.User")
                        .WithMany("Animals")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("JO.Data.AnimalType", b =>
                {
                    b.HasOne("JO.Data.AnimalStats", "Stats")
                        .WithMany()
                        .HasForeignKey("StatsAnimalStatsId");
                });
#pragma warning restore 612, 618
        }
    }
}
