// <auto-generated />
using JO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace JO.Data.Migrations
{
    [DbContext(typeof(VirtualPetContext))]
    [Migration("20170720212401_VirtualPet20170720")]
    partial class VirtualPet20170720
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-preview2-25794");

            modelBuilder.Entity("JO.Data.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnimalTypeId");

                    b.Property<float>("CurrentHappiness");

                    b.Property<float>("CurrentHunger");

                    b.Property<int?>("MetricAnimalMetricId");

                    b.HasKey("AnimalId");

                    b.HasIndex("MetricAnimalMetricId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("JO.Data.AnimalMetric", b =>
                {
                    b.Property<int>("AnimalMetricId")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("HappinessDecreaseRate");

                    b.Property<float>("HappinessIncreaseRate");

                    b.Property<float>("HungerDecreaseRate");

                    b.Property<float>("HungerIncreaseRate");

                    b.HasKey("AnimalMetricId");

                    b.ToTable("AnimalMetrics");
                });

            modelBuilder.Entity("JO.Data.AnimalType", b =>
                {
                    b.Property<int>("AnimalTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MetricId");

                    b.Property<string>("Type");

                    b.HasKey("AnimalTypeId");

                    b.HasIndex("MetricId");

                    b.ToTable("AnimalTypes");
                });

            modelBuilder.Entity("JO.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Name");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JO.Data.UserOwnedAnimal", b =>
                {
                    b.Property<int>("UserOwnedAnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AnimalId");

                    b.Property<string>("Name");

                    b.Property<int?>("UserId");

                    b.HasKey("UserOwnedAnimalId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOwnedAnimals");
                });

            modelBuilder.Entity("JO.Data.Animal", b =>
                {
                    b.HasOne("JO.Data.AnimalMetric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricAnimalMetricId");
                });

            modelBuilder.Entity("JO.Data.AnimalType", b =>
                {
                    b.HasOne("JO.Data.AnimalMetric", "Metric")
                        .WithMany()
                        .HasForeignKey("MetricId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JO.Data.UserOwnedAnimal", b =>
                {
                    b.HasOne("JO.Data.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JO.Data.User")
                        .WithMany("UserOwnedAnimals")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
